require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::ReviewsController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Review. As you add validations to Admin::Review, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::ReviewsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all review as @review" do
      review = FactoryGirl.create :employee
      get :index, {}
      assigns(:reviews).should eq([review])
    end
  end
=begin
  describe "GET show" do
    it "assigns the requested admin_review as @admin_review" do
      review = Admin::Review.create! valid_attributes
      get :show, {:id => review.to_param}
      assigns(:admin_review).should eq(review)
    end
  end
=end

  describe "GET edit" do
    it "assigns the requested review as @review" do
      review = FactoryGirl.create :employee
      get :edit, {:id => review.to_param}
      assigns(:review).should eq(review)
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested review" do
        review = FactoryGirl.create :employee
        put :update, {:id => review.to_param, :employee => { score: 100 }}
      end

      it "assigns the requested review as @review" do
        review = FactoryGirl.create :employee
        put :update, {:id => review.to_param, :employee => {score: 100}}
        assigns(:review).should eq(review)
      end

      it "redirects to the review" do
        review = FactoryGirl.create :employee
        put :update, {:id => review.to_param, :employee => {score: 100}}
        response.should redirect_to(admin_reviews_path)
      end
    end

    describe "with invalid params" do
      it "assigns the review as @review" do
        review = FactoryGirl.create :employee
        # Trigger the behavior that occurs when invalid params are submitted
        Employee.any_instance.stub(:save).and_return(false)
        put :update, {:id => review.to_param, :employee => {  }}
        assigns(:review).should eq(review)
      end

      it "re-renders the 'edit' template" do
        review = FactoryGirl.create :employee
        # Trigger the behavior that occurs when invalid params are submitted
        Employee.any_instance.stub(:save).and_return(false)
        put :update, {:id => review.to_param, :admin_review => {  }}
        response.should render_template("edit")
      end
    end
  end

end
